name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Docker Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Copy Project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/my-devops-project"

      - name: Deploy Application
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "=============================="
            echo "Changing directory"
            echo "=============================="

            cd /home/ubuntu/my-devops-project

            pwd
            ls -la

            echo "=============================="
            echo "Running Containers"
            echo "=============================="

            docker ps -a || true

            echo "=============================="
            echo "Stopping Existing Container"
            echo "=============================="

            docker stop mywebsite || true
            docker rm mywebsite || true

            echo "=============================="
            echo "Removing Container Using Port 80"
            echo "=============================="

            CONTAINER=$(docker ps -q --filter "publish=80")

            if [ -n "$CONTAINER" ]; then
              docker stop $CONTAINER
              docker rm $CONTAINER
            fi

            echo "=============================="
            echo "Removing Old Image"
            echo "=============================="

            docker rmi mywebsite || true

            echo "=============================="
            echo "Building Docker Image"
            echo "=============================="

            docker build -t mywebsite .

            echo "=============================="
            echo "Starting Container"
            echo "=============================="

            docker run -d \
              --name mywebsite \
              --restart unless-stopped \
              -p 80:80 \
              mywebsite

            echo "=============================="
            echo "Deployment Successful"
            echo "=============================="

            docker ps
